bracketSpacing: false
endOfLine: lf
jsxSingleQuote: true
printWidth: 120
singleQuote: true
tabWidth: 2
overrides:
  - files:
      - '.vscode/*.json'
    options:
      tabWidth: 4
  - files:
      - '*.md'
    options:
      singleQuote: false
