name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ $${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          cache: pnpm
          node-version-file: '.node-version'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm check-format

      - name: Run tests
        run: pnpm test --ci --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        if: always()
        with:
          directory: coverage

      - name: Build production bundle
        run: pnpm build

      - name: Build Storybook
        run: pnpm build-storybook
