name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  NODE_VERSION: 16

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Yarn configuration
        id: yarn-config
        shell: bash
        run: |
          echo "INSTALL_STATE_PATH=$(yarn config get installStatePath)" >> $GITHUB_OUTPUT
          echo "PNP_UNPLUGGED_FOLDER=$(yarn config get pnpUnpluggedFolder)" >> $GITHUB_OUTPUT

      - name: Restore Yarn install state
        id: yarn-install-state-cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          path: |
            ${{ steps.yarn-config.outputs.INSTALL_STATE_PATH }}
            ${{ steps.yarn-config.outputs.PNP_UNPLUGGED_FOLDER }}

      - name: Install dependencies
        run: yarn install --immutable --inline-builds
        env:
          HUSKY: 0 # Disable Husky hooks installation

      - name: Run tests
        run: yarn test --ci --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Restore build cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          key: ${{ runner.os }}-build-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}-${{ hashFiles('src/**.tsx?', 'package.json', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}-
          path: |
            ${{ github.workspace }}/node_modules/.cache

      - name: Build production bundle
        run: yarn build
