name: CI

on:
  push:
    branches: [main, 'renovate/**', 'feat/**', 'fix/**']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  NODE_VERSION: 16

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure Yarn
        id: yarn-config
        shell: bash
        run: |
          echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Use Yarn cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        id: yarn-cache
        with:
          path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        run: yarn install --immutable --inline-builds

      - name: Run tests
        run: yarn test

      - name: Build production bundle
        run: yarn build
