name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ $${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.12.1 # renovate: datasource=node depName=node

      - name: Get Yarn configuration
        id: yarn-config
        shell: bash
        run: |
          echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
          echo "INSTALL_STATE_PATH=$(yarn config get installStatePath)" >> $GITHUB_OUTPUT

      - name: Restore Yarn cache
        id: yarn-cache
        uses: actions/cache@c17f4bf4666a8001b1a45c09eb7a485c41aa64c3 # v3.2.0
        with:
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
          restore-keys: |
            yarn-cache-

      - name: Restore Yarn install state
        id: yarn-install-state-cache
        uses: actions/cache@c17f4bf4666a8001b1a45c09eb7a485c41aa64c3 # v3.2.0
        with:
          key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          path: ${{ steps.yarn-config.outputs.INSTALL_STATE_PATH }}

      - name: Install dependencies
        run: yarn install --immutable --inline-builds
        env:
          HUSKY: 0 # Disable Husky hooks installation
          YARN_NM_MODE: 'hardlinks-local'

      - name: Run tests
        run: yarn test --ci --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        if: always()
        with:
          directory: coverage

      - name: Restore build cache
        uses: actions/cache@c17f4bf4666a8001b1a45c09eb7a485c41aa64c3 # v3.2.0
        with:
          key: ${{ runner.os }}-build-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}-${{ hashFiles('src/**.tsx?', 'package.json', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}-
          path: |
            ${{ github.workspace }}/node_modules/.cache

      - name: Build production bundle
        run: yarn build
